source            : ./source
destination       : ./output
plugins           : ./source/_plugins
syntaxhighlighter : ../SyntaxHighlighter

markdown    : maruku
permalink   : /:year/:month/:title
auto        : true

